### ISSUE TITLE
Custom Saver to pass custom objects to screens

### ISSUE THREAD

**Issue by kevinvanmierlo** [hristogochev/vortex#1]
First of all, nice work on the rewrite / simplification! Like I said in the Voyager thread, this will probably solve a lot of issues I had with Voyager.  I'll copy the rest of the text from that thread:

> However, I don't like that you forced the default navigation saver. It's fine that it's the default, but I prefer passing objects to the next screen without making them serializable or something. I created a custom saver for Voyager which just saves the list to a Map and it will just revert back to the initial screen when destroyed. 

I don't want to spend a lot of time on making sure every screen is Serializable. Mostly I just want to pass an object I just fetched from the server. I don't want to refetch it on the detail page or make sure the full item is Serializable. In Voyager the way I did this was like this:
```Kotlin
object KMNavigatorSaver {
    val saverMap = mutableMapOf<String, List<Screen>>()
}

@OptIn(ExperimentalVoyagerApi::class, InternalVoyagerApi::class)
public fun kmNavigatorSaver(): NavigatorSaver<String> = NavigatorSaver { initialScreens, key, stateHolder, disposeBehavior, parent ->
    Saver(
        save = {
            val uuid = UUID.randomUUID().toString()
            KMNavigatorSaver.saverMap[uuid] = it.items
            uuid
        },
        restore = {
            val items = KMNavigatorSaver.saverMap[it]
            KMNavigatorSaver.saverMap.remove(it) // Remove so we don't keep everything in memory all the time
            Navigator(items ?: initialScreens, key, stateHolder, disposeBehavior, parent)
        }
    )
}

@OptIn(ExperimentalVoyagerApi::class)
@Composable
public fun KMNavigator(
    screen: Screen,
    disposeBehavior: NavigatorDisposeBehavior = NavigatorDisposeBehavior(
        disposeNestedNavigators = false,
    ),
    onBackPressed: OnBackPressed = { true },
    content: NavigatorContent = { ScreenBasedTransition(navigator = it) }
) {
    CompositionLocalProvider(
        LocalNavigatorSaver provides kmNavigatorSaver()
    ) {
        Navigator(
            screen = screen,
            disposeBehavior = disposeBehavior,
            onBackPressed = onBackPressed,
            content = content
        )
    }
}
```

There was a small issue though. Because I couldn't access Voyager internals, sometimes items from the map wouldn't get removed properly. So I'm not sure to support this as another option or just allow to override a saver like in Voyager?

**Comment by hristogochev** [comment]
This seem really useful! 

I've brought back this functionality from Voyager and it's now in the [1-custom-saver-to-pass-custom-objects-to-screens](https://github.com/hristogochev/vortex/tree/1-custom-saver-to-pass-custom-objects-to-screens) branch.

I've also updated the documentation and used your case as an example [here](https://github.com/hristogochev/vortex/blob/1-custom-saver-to-pass-custom-objects-to-screens/docs/state-restoration.md#custom-state-restoration-mechanism).

My only problem with your solution is that you call `KMNavigatorSaver.saverMap.remove(it)` on `restore`, and I believe that `restore` can be called multiple times after `save`.

I will merge it into the main branch and create a release if it satisfies your case.

**Comment by hristogochev** [comment]
Now that I look at it, maybe we can make it so that we don't need screens to be serializable at all, so that there is no need for custom navigator savers.

We can just rely on an `NavigatorStore`, like we do with `ScreenModelStore`, the only problem then would be no restoration upon Process Death ( which is not already not supported for ScreenModels and wasn't supported for them in Voyager either ).

**Comment by kevinvanmierlo** [comment]
Wow you're quick! I'll have to check it out. I'll probably have some time this week. Oh really? I never had any issues with this implementation, but haven't checked if it is called multiple times. I just didn't want to keep everything in memory longer than needed.

I want to create a sample project which tests some of the issues I had on voyager. So it will have a tabbar with navigators inside the tabbar and around the tabbar. And then handle some navigation. As long as everything is in the stack it will need to should not get disposed. If it is removed from the stack it should get disposed. Also it needs to remember the scroll position and everything where rememberSaveable is used. 

Voyager made everything Serializable so it always handles state restoration. And you have to actively turn it off, like I did. It depends what you want the default to be as library maker. I think it's noble to try and handle the state restoration, but I found it to be too much of a hassle and it works perfectly without it for me. 
So it's up to you if you want it or not. As long as it's supported it's fine for me :). 
But I think it would be fine if the default isn't Serializable and just provide the options to support it. 

If we can just rely on the NavigationStore that would be great!

**Comment by hristogochev** [comment]
Having such NavigatorStore which allows screens not to be serializable does not harm the state restoration in any way, all screens and their parameters and properties still get properly restored. In fact, I don't see a benefit from forcing screens to be serializable to allow for state restoration, it's purely a design choice, as far as I can tell.

**Comment by kevinvanmierlo** [comment]
Well the data needs to be written in some kind of rememberSaveable right to be able to fully support stat restoration right? The NavigatorStore would only be working as long as the app is running.

**Comment by hristogochev** [comment]
You are correct. I totally forgot about process death :sweat_smile:. In that case the default saver will remain to require serializable variables and custom savers will be an addition.

**Comment by kevinvanmierlo** [comment]
Haha no worries! You could also make it that the Screen doesn't support Serializable. And add a SerializableScreen if people want to support it. That way you don't always have a Serializable Screen. I didn't encounter any issues. But always thought it was weird that my Screen is Serializable but if the serialize function would've been called, my app would crash

**Comment by hristogochev** [comment]
I've updated the branch and documentation with a mechanism to correctly cleanup navigators when they are disposed.

**Comment by kevinvanmierlo** [comment]
Awesome! I'll try to check it out this week and make the test project I talked about earlier

**Comment by kevinvanmierlo** [comment]
@hristogochev Overall most seems to work very nice. I did discover one issue with disposing the navigator and its childs. I have this setup: Navigator -> Tabbar (Navigator) with three tabs -> Tab (Navigator). So you can navigate outside the tabbar (next screen no tabbar) and inside the tabbar. If I click on a tab, push a new screen, go to another tab, navigate to a new screen outside the tabbar and then replace everything to a new tabbarscreen. Everything works fine then. But If I click on a tab, click on another tab, go back to the tab, push a new screen, go to another tab, navigate to a new screen outside the tabbar and then replace everything to a new tabbarscreen. Then the tab where we pushed the second screen doesn't get disposed. Hopefully this makes sence, it's a lot of text 😅 If you need the test project, I can provide it. Here are some logs which hopefully makes more sense:

```
Start tab Favorites
Start screen TestScreen Tab1#2-0
Start tab Profile
Start screen TestScreen Tab2#2-0
Start screen TestScreen Tab2#2-1
Start screen TestScreen Tab1#2-1
Start screen TestScreen #0-0

Start screen TabBarScreen
Start tab Home
Start screen TestScreen Tab0#2-0
TabBarScreenModel: dispose
TabScreen: dispose Home
TestScreen: dispose Tab0#2-0
Dispose screen TestScreen Tab0#2-0
Dispose tab Home
TabScreen: dispose Favorites
TestScreen: dispose Tab1#2-0
Dispose screen TestScreen Tab1#2-0
Dispose tab Favorites
TabScreen: dispose Profile
TestScreen: dispose Tab2#2-0
Dispose screen TestScreen Tab2#2-0
TestScreen: dispose Tab2#2-1
Dispose screen TestScreen Tab2#2-1
Dispose tab Profile
Dispose screen TabBarScreen
TestScreen: dispose #0-0
Dispose screen TestScreen #0-0
```

I placed a log inside the `ScreenDisposableEffect` and the `ScreenModel` for each `Screen`.  The logs begin when the app is started (So TabBarScreen and Home is already started). So here you can see I'm starting Tab1#2-1, but it never gets disposed. I think maybe it creates a new Navigator the second time we go to the Tab and it remembers that, but still has the first Navigator in memory for the cleanup action. Let me know if I need to provide some more information.

**Comment by kevinvanmierlo** [comment]
Here is the code I used. I merged everything to a single file, so it is easier to test: 

```Kotlin
@file:SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")

package io.github.hristogochev.vortex.sample.customSaver

import android.annotation.SuppressLint
import android.os.Bundle
import android.util.Log
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.RowScope
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Favorite
import androidx.compose.material.icons.filled.Home
import androidx.compose.material.icons.filled.Person
import androidx.compose.material3.Button
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.NavigationBar
import androidx.compose.material3.NavigationBarItem
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.Saver
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.rememberVectorPainter
import androidx.compose.ui.unit.dp
import io.github.hristogochev.vortex.model.ScreenModel
import io.github.hristogochev.vortex.model.rememberScreenModel
import io.github.hristogochev.vortex.navigator.LocalNavigator
import io.github.hristogochev.vortex.navigator.LocalNavigatorSaverProvider
import io.github.hristogochev.vortex.navigator.Navigator
import io.github.hristogochev.vortex.navigator.NavigatorSaverProvider
import io.github.hristogochev.vortex.screen.CurrentScreen
import io.github.hristogochev.vortex.screen.Screen
import io.github.hristogochev.vortex.screen.ScreenDisposableEffect
import io.github.hristogochev.vortex.screen.uniqueScreenKey
import io.github.hristogochev.vortex.tab.CurrentTab
import io.github.hristogochev.vortex.tab.Tab
import io.github.hristogochev.vortex.transitions.SlideTransition
import io.github.hristogochev.vortex.util.ThreadSafeSet
import io.github.hristogochev.vortex.util.currentOrThrow

class CustomSaverActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContent {
            Content()
        }
    }

    @SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")
    @Composable
    fun Content() {
        KMNavigator(TabBarScreen())
    }
}

fun Navigator.getRootNavigator(): Navigator {
    var navigator: Navigator = this
    while(navigator.parent != null) {
        navigator = navigator.parent!!
    }
    return navigator
}

object NavigatorsStore {
    // A mutable map of navigators, that takes the navigators' keys as keys,
    // and their screens and screenStateKeys as values
    val navigators: MutableMap<String, Map<String, Any>> = mutableMapOf()
}

data object ExternalNavigatorSaverProvider : NavigatorSaverProvider<String> {
    override fun provide(parent: Navigator?): Saver<Navigator, String> {
        return Saver(
            save = { navigator ->
                // We need to use `.toList()` to create a copy of the items and screen state keys,
                // otherwise their references will be used, which will not work
                val contentsMap = mapOf(
                    "items" to navigator.items.toList(),
                    "screenStateKeys" to navigator.getAllScreenStateKeys().toList()
                )

                // Save the current navigator contents into an outside map, using its key
                NavigatorsStore.navigators[navigator.key] = contentsMap

                // Only tell our saver about the navigator's key, since we manage the saving externally
                navigator.key
            },
            restore = restore@{ key ->
                // If there are no saved contents for the navigator by it's key,
                // forget the current saved one and recreate the navigator
                val navigatorContents = NavigatorsStore.navigators[key] ?: return@restore null

                // If any of the core components of a navigator are missing,
                // forget the current saved one and recreate the navigator
                @Suppress("UNCHECKED_CAST")
                val savedScreens =
                    navigatorContents["items"] as? List<Screen> ?: run {
                        NavigatorsStore.navigators.remove(key)
                        return@restore null
                    }

                @Suppress("UNCHECKED_CAST")
                val savedScreenStateKeys =
                    navigatorContents["screenStateKeys"] as? List<String> ?: run {
                        NavigatorsStore.navigators.remove(key)
                        return@restore null
                    }

                Navigator(
                    initialScreens = savedScreens,
                    key = key,
                    parent = parent,
                    screenStateKeys = ThreadSafeSet(savedScreenStateKeys)
                )
            }
        )
    }

    override fun dispose(navigator: Navigator) {
        // When a navigator is disposed make sure to clean up the NavigatorsStore
        NavigatorsStore.navigators.remove(navigator.key)
    }
}

@Composable
public fun KMNavigator(
    screen: Screen,
) {
    CompositionLocalProvider(
        LocalNavigatorSaverProvider provides ExternalNavigatorSaverProvider
    ) {
        Navigator(
            screen = screen,
        ) { navigator ->
            CurrentScreen(
                navigator = navigator,
                defaultOnScreenAppearTransition = SlideTransition.Horizontal.Appear,
                defaultOnScreenDisappearTransition = SlideTransition.Horizontal.Disappear
            )
        }
    }
}

abstract class BaseScreen : Screen {
    override val key: String = uniqueScreenKey()
}

abstract class BaseTab : Tab {
    override val key: String = uniqueScreenKey()
}

class TabBarScreenModel : ScreenModel {
    override fun onDispose() {
        Log.d("TEST", "TabBarScreenModel: dispose")
    }
}

class TabBarScreen : BaseScreen() {
    @OptIn(ExperimentalMaterial3Api::class)
    @Composable
    override fun Content() {
        val screenModel = rememberScreenModel { TabBarScreenModel() }

        ScreenDisposableEffect {
            Log.d("TEST", "Start screen TabBarScreen")
            onDispose {
                Log.d("TEST", "Dispose screen TabBarScreen")
            }
        }

        Navigator(screen = HomeTab) { navigator ->
            Scaffold(
                topBar = {
                    val title = when ((navigator.current as Tab).index) {
                        0u -> "Home"
                        1u -> "Favorites"
                        2u -> "Profile"
                        else -> "Unknown"
                    }
                    TopAppBar(
                        title = {
                            Text(text = title)
                        }
                    )
                },
                content = { innerPadding ->
                    CurrentTab(navigator)
                },
                bottomBar = {
                    NavigationBar {
                        TabNavigationItem(HomeTab)
                        TabNavigationItem(FavoritesTab)
                        TabNavigationItem(ProfileTab)
                    }
                }
            )
        }
    }

    @Composable
    private fun RowScope.TabNavigationItem(tab: Tab) {
        val navigator = LocalNavigator.currentOrThrow

        val painter = when (tab.index) {
            0u -> rememberVectorPainter(Icons.Default.Home)
            1u -> rememberVectorPainter(Icons.Default.Favorite)
            2u -> rememberVectorPainter(Icons.Default.Person)
            else -> return
        }

        val title = when (tab.index) {
            0u -> "Home"
            1u -> "Favorites"
            2u -> "Profile"
            else -> return
        }

        NavigationBarItem(
            selected = navigator.current.key == tab.key,
            onClick = {
                navigator.current = tab
            },
            icon = {
                Icon(
                    painter = painter,
                    contentDescription = title
                )
            }
        )
    }
}

data object FavoritesTab : BaseTab() {
    override val index: UInt = 1u

    @Composable
    override fun Content() {
        TabContent()
    }
}

data object HomeTab : BaseTab() {
    override val index: UInt = 0u

    @Composable
    override fun Content() {
        TabContent()
    }
}

object ProfileTab : BaseTab() {
    override val index: UInt = 2u

    @Composable
    override fun Content() {
        TabContent()
    }
}

class TestScreenModel : ScreenModel {
    var inTab = ""
    var depth = 0
    var index = 0

    override fun onDispose() {
        Log.d("TEST", "TestScreen: dispose ${inTab}#${depth}-${index}")
    }
}

class TestScreen(val inTab: String = "", val index: Int = 0): BaseScreen() {
    @OptIn(ExperimentalLayoutApi::class)
    @Composable
    override fun Content() {
        val screenModel = rememberScreenModel { TestScreenModel() }
        val navigator = LocalNavigator.currentOrThrow
        val depth = remember {
            var i = 0
            var parent = navigator.parent
            while(parent != null) {
                i++
                parent = parent.parent
            }
            i
        }
        LaunchedEffect(index, depth) {
            screenModel.inTab = inTab
            screenModel.index = index
            screenModel.depth = depth
        }

        ScreenDisposableEffect {
            Log.d("TEST", "Start screen TestScreen ${inTab}#${depth}-${index}")
            onDispose {
                Log.d("TEST", "Dispose screen TestScreen ${inTab}#${depth}-${index}")
            }
        }

        Column(
            verticalArrangement = Arrangement.Center,
            horizontalAlignment = Alignment.CenterHorizontally,
            modifier = Modifier.fillMaxSize()
        ) {
            Text(
                text = "Screen #${depth}-$index",
                style = MaterialTheme.typography.headlineSmall
            )

            Spacer(modifier = Modifier.height(24.dp))

            FlowRow(
                modifier = Modifier.padding(16.dp)
            ) {
                Button(
                    enabled = navigator.canPop,
                    onClick = navigator::pop,
                ) {
                    Text(text = "Pop inside")
                }

                Spacer(modifier = Modifier.width(20.dp))

                Button(
                    enabled = navigator.parent != null && navigator.getRootNavigator().canPop,
                    onClick = {
                        navigator.parent?.pop()
                    },
                ) {
                    Text(text = "Pop outside")
                }

                Spacer(modifier = Modifier.width(20.dp))

                Button(
                    onClick = { navigator.push(TestScreen(inTab = inTab, index = index.inc())) },
                ) {
                    Text(text = "Push inside")
                }

                Spacer(modifier = Modifier.width(20.dp))

                Button(
                    enabled = navigator.parent != null,
                    onClick = { navigator.getRootNavigator().push(TestScreen(index = 0)) },
                ) {
                    Text(text = "Push outside")
                }

                Spacer(modifier = Modifier.width(20.dp))

                Button(
                    onClick = {
                        navigator.replaceAll(
                            TabBarScreen()
                        )
                    }
                ) {
                    Text(text = "Replace All")
                }
            }

            LazyColumn(
                modifier = Modifier.fillMaxSize()
            ) {
                items(100){ item->
                    Text("Item #${item}")
                }
            }
        }
    }
}

class TabScreenModel : ScreenModel {
    var tabTitle = ""

    override fun onDispose() {
        Log.d("TEST", "TabScreen: dispose ${tabTitle}")
    }
}

@Composable
fun Tab.TabContent() {
    val tabTitle = when (index) {
        0u -> "Home"
        1u -> "Favorites"
        2u -> "Profile"
        else -> "Unknown"
    }

    val screenModel = rememberScreenModel { TabScreenModel() }
    LaunchedEffect(index) {
        screenModel.tabTitle = tabTitle
    }

    ScreenDisposableEffect {
        Log.d("TEST", "Start tab $tabTitle")
        onDispose {
            Log.d("TEST", "Dispose tab $tabTitle")
        }
    }
    KMNavigator(TestScreen(inTab = "Tab$index"))
}
```

**Comment by hristogochev** [comment]
Thank you for finding this! 

I found the reason this is happening, published a new release (0.1.2) and updated the branches.

Can you check if it works for you now?

**Comment by kevinvanmierlo** [comment]
It is working now! Thank you :) 

It's up to you, but maybe you can add the SaverProvider I used to the library itself? I'm not sure if there are many people like me that want to use the navigator like this. But if there are, it would be nice to only write the `CompositionLocalProvider` and not have to copy the complete SaverProvider. What do you think?

**Comment by hristogochev** [comment]
I thought about adding it too, and I think I will push it in the next release. Are there any other things stopping you from migrating to Vortex?

**Comment by kevinvanmierlo** [comment]
Thanks! It's your choice if you want to add it, so I'll see if you have added it later on ;) 
I think I've got everything I need. I wanted to look at predictive back gesture and swipe to go back later. I have implemented it in Voyager, but I'll cross that bridge later.

**Comment by kevinvanmierlo** [comment]
@hristogochev You still need to create a release with the custom savers right? No rush, but do you know when you are planning the release for it?

**Comment by hristogochev** [comment]
I'm still not satisfied with the public API for custom navigator savers, I will publish a release after I'm satisfied with it, while keeping the same functionality

**Comment by hristogochev** [comment]
I've published a release (0.2.0) which contains the changes.

**Comment by kevinvanmierlo** [comment]
Awesome, thanks!
